//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public int MaNV { get; set; }
        public System.DateTime GioVao { get; set; }
        public System.DateTime GioRa { get; set; }
        public long TongTien { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<int> MaPhieuPhat { get; set; }
        public Nullable<int> MaHDDV { get; set; }
        public Nullable<int> MaPhieuDat { get; set; }
    
        public virtual HDDichVu HDDichVu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhieuDat PhieuDat { get; set; }
        public virtual PhieuPhat PhieuPhat { get; set; }
    }
}
