//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDat()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaPhieu { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayNhan { get; set; }
        public string LoaiPhieu { get; set; }
        public string HoTenKH { get; set; }
        public string CMND { get; set; }
        public string SoDienThoai { get; set; }
        public int SoLuongKH { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<long> TienCoc { get; set; }
        public Nullable<long> PhiTiec { get; set; }
        public Nullable<int> MaTiec { get; set; }
        public Nullable<int> MaPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual Tiec Tiec { get; set; }
    }
}
