//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangBi
    {
        public int MaPhong { get; set; }
        public int MaTB { get; set; }
        public int SL { get; set; }
        public string TrangThai { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
